language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - 174.138.11.19
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/var/bot/
  - REMOTE_USER=deploy
  - REMOTE_HOST=174.138.11.19
  - secure: JGFcpBhOmvNw7Cj2iX9tvWa6LKH+O39mpZwLMEnBXWvlZ8QgQk5fUZ9Oj4fJ8LYAgVV60QEX/ZIpag3vyvRPb6Mnemw7t/ExzLNSivKCNCzbKAmIgUrH0O7QmFGdIg8M6Da+nHKQ8w0yphrJKWpHf8azok+wzYtmNHgvJLgOsGS2fHEpOyW+MQYYhlj3NvaPLcFidlZHrujD6eBrH2IQ514dutkwhlSq4GcuHfaeV1nF4TJS2jA497gSuCbe4dGy8xY24k5wAalIPabRDNwjmV79ZB4rlcSoVHxUGrp8fzfA/PNPPowMOID4e9ca6dCjcSTA/lQFwavwPAcZ8hIGMuWSUExpU/n9pdwESFI2mOtDDS2kjTOPHkx3TTgm8J9wcqLoUyetBx19/6M1sThzMQLOG3coXuMatDUXvGriXkBVYq/ySIAV9rKqouFkwder8jnXlqvAwQT5yTiEPF5fdqR7sxh8uiUW5MZsIWj6EbHvwRdMWw/SAwCKlgnwzYqMa+M9jJ9CeDaeD3oXoszZdql+JCD6JICzrfGBgdgNDYowpz0B3odK41Om8PGl5kK9nKwOgvQhQ4GS1vk4m6c308egS3SqcIXDaBTQFBY9MZzuZv83ekkiDvfjDMvszZJ2V64/Dg1VsFdVBXfG4/CKvhRBYnacmjiEft5Dc59k05E=
  - secure: lZwZL9lCjTidLNf/EUNEK+7z/9HwGRnQ9UuFGdO3rxBXTn0FWk/MnVvUvwoc+0HXonfPSQVBYHYGG3DPkGrFzhl9KfaWZtUzu84N4I34DclpRgZwAZbg7wpBiYXfOwh4QG3N4Ik+0XZ5S9cdfy2pMxZuC92eCofoJzQrM+bsEk5PyMYizPjY0xd4fwqzjzYjIUSKdqGc4ZeyOc6bAhDFHr5UhNyrK07G6Vynzpdy6PHGyKnWiiSKLjzjRGwus5ywKizDsuS/deS8d4BL0lKoVZL3ESyTjbxx9Gps4QOGgxvBd5TlsJ/JTITKy+Faucx6lxr+mgB8S8bs93uJsMBM6E3F7Wf5bBopydur6avnduhI7M1B6RmHEMx8iCcBt+KqECzBZl76Nk6njqCI5CIuKgbvNiwaBnICbOwpYh6lWQ01pHdXDGlTEhrV6ivb+Gqj7hH1LpmED3xscw2vuIu/cuR5UPfKvZV9MEHH/hKn4meCfiErkuBR23Tt0erxQRRc0AkrlyDAhJWTXpTEd8sC5fL+ibebI5nDgkmZXL9qIS9SYlfmMneMf6+dGqhv+/OrqiPv2AT7uV7gLiptwDue8nJkUAmplX41/jDEr85eH6AQoahuDF1ts/JiQDatJZnb+Y96/EjGakq+V2NCjYViMZ3Rzkn7ybc+W7UYFhW5K6o=
  - secure: ltNvTiJaA5t1EwCzrcoHCULqG22pQmVE2pxqsQCDSCqGbQnLH+v7wDwudcVmamfKmbxXQ5fPldKFyVdwExQoj/kYxp+2sEM1EmWGF8C4kRz8RAN/AK+72Q4OCbUviMDO8AZ2vjd8lKjt8vjV19ftpYghRDsWAKFtAtD9MwVg6nDAZoGjckn6Qn3HJqmCurQQX0u6COJ+Eqbf6x3d8tIgSOuqJg9SOya1zTDqjkqXFQGo7ZCYNJJBVW2SZtPrMTnVgX31Xqh0z26GXGe26QGJglfS5qhxHFRoFihYmjPlmfgjOFljx2suj/KLCQPC2Xkg6iMMrZQCLMJvSWpj3BBc+/pbv9GMOe3Xp1ieem0hwUAWGlojb+LT4DgeT6TN95E0JOWhtXWLuizGz8ANumNdARVMIp/NK95Z8XP2Wb5iSuGfc4eD5FiRVeaIvSXbSSUvnXF4fGM1GuxE98x6cnv2vi7TXO7TBTQkHyan6ZsmVuyP9zp+hx0ayKFe1IuZ+a8g76gMuPtsfu7zqReeqKC3L2XUfUS5kJmp8CIdjKt9HZIRlS8UfrX+6Jb/7kvxqwVf5YQz+3w1NeNQAf/qoK4UqRAQKJPg9Phzwz7/Syv0/zpp1G8nLqNunCUosY7OrRsxDVtCbWlrMA7tcpTAWr0VDJ1k7YTY+EMtf1vyDArYPFE=
before_install:
- openssl aes-256-cbc -K $encrypted_14dfe625469c_key -iv $encrypted_14dfe625469c_iv
  -in deploy-key.enc -out deploy-key -d
- sudo apt-get -qq update
- sudo apt-get install -y jq
install:
- npm install --only=dev
script:
- npm run build
after_success:
- "./scripts/deploy.sh"
