language: node_js
node_js:
- node
addons:
  ssh_known_hosts:
  - 174.138.11.19
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/var/bot/
  - REMOTE_USER=deploy
  - REMOTE_HOST=174.138.11.19
  - secure: C2j7ByAwEo+DCvpZRx5shMAeeLXRRHNPZRoTz43kG1f5knqrkj8eFaG0YP/uL+pQpQOYZ/GgO/7z/hONsgpJS5AZfaeHnDpMzfue80o1eNTW3XrppD+jzwTiJpxDTmnSUVK1Mg6bhtT4PNYD0MIE5qq8WpfrlRcNjFWAeo5pH5Cwx9FlL8LhJRafLAfvdXDmL/HV+rh5eUIyyx3BJ9w5j3qw0cuNZojoh/ZEzyZfMsOlB4vVwVmzIjMsdGyq9M+bq8odb2Qlw29j06FAvwvP0cfJvrcaOt4itNNcdulrvg1THcYVXetEootiKS6hJixJ3IUdPeIfSNRFvpWwwSJyOLgbeZLHQhj5IsM01kvqtknkCavhcmBNJAS1DrVZnGLaLCnmXsAN/ZKfBwBd0N0P/p629i0/MCGcvKhWc9/gwgrGzHovw4olnOmo2GWAvxnQOXSPXGmbikduqPGuBFIGvTZq8g4q4kZGxqol47l6UYGxs3bRxnVCTd9SmaWd7ik1pgw3CC5BhDhP3fQW56e52IJRgPGTfLZIlbxjrxyGdz3XN5Mik0BlNgsXZsQf/Jrzb1GofjNeH1Syp9abbeanXZj9yjI+XOGKVQChmPXRxpG7W76HwpwF0Uh+6SJq3WrlyY87C+AxGhdDTz/Hr5AMI7VOjPmGNSYFnQAuIYpzGI0=
  - secure: HXyFYBbDvFRcnofbIqkAQpnPQZZfgy8vmDwpVrY6dg/qbo4HhRdg8q6J0Nfr9Yf+oNL/B4yFqipjp4r988kZkNf2IPuAP8hlOec7mcHN+NfPA7xrs3J8AR/cEq8ZoVFjgo1LaVceHuFGwIhhTWnQkv6bz3k5odQ0JnE8iHjXYGscHgk386ew5/8WonBg21Oo+Y4f8Cz+LzCMQfk2rWhS2JsUAulzxYHSQ0mPUv7esjSQe61crzYMkr/5KuEL5am4ntqfyDo3Qic0dbcAsrsJ5/e1dqQ3D/HuEvZ98HmJbkG9untIHMkOKHPVA3DiQFBYjD6rrsW25ZaLbtFlEPlu0fbLSUeqzzVe4Wc3V1gpfbsthHGTl9N8y3AJB8Os9LWrUfPqCzKFCWyZEVIhzDUKUstrgZtcmvLzOv3tjop7RDBCh7nYwCaBUFiW2KCmxEOzpBWI31h22lUiDgzx9lWfA6qqvTHtIpfc1xYt8cNWCmyuGU4aZv2a3mPPdrayiBSuXcFXCD24af6zEqhG3YDJYtALZAAEEm0l8goC21czEyWpx48jZZ2WgsHcEU0Dm0SAsw2OJEVR3OmJ06n19HK7kWbLQCzcHOeTizSVSQIqpskJ0zlnEkYirXqt5t/2awI8MnIDz5tfnSm/SwwvkzPOmQX5HEDxrbBbz2Y+gau9xqw=
  - secure: N5kXeFVNlNVV1Jy8TJMviCT3tUtDYSyXDQyziEbv6PIuhN/zYjFbufbkCwKpyJAV+YSzZf+hL007kRyLH6SdzM8/J5hYdnZaR1rpe7mo5bGhYmwSahqlN4QzfrUZ0HQBUCyP07SOG+3ip+nvPHx+/68AXfMd+E79qfK612cgz0almgfKhhjDJTUzetcIu9Imp926VV1mjSEtGX9WvfIvBM04M2b1lAmjmjp5poEfZ4hqy95NSokzVwuPOE0IjP9J+jifZQpsWvJVYdk/XLw5n2bQt+T/pQdQhHHe4aTaK354ieqV9e+c+0YNN4S7n5WT0DKJiuAOoboZOiFDdmNkDWG0zZzi+HZaF0ZPoENc/dBcCKvJP3ul+em9zGAVV8qi25z6OHzVjPaAw+jVJfGM/OGn0Cp3fi5lr7uZzQ8VOSG9Y1OhFLg4Yhw9EMIWdM8226j3BqcgAyGH9CtW6k4CZlUX4TCpZm6moVzVSX5O8rkfVVf7xquMCaUuACT7xGTKeVEH2y+0AV/KhLeAioSiK4cNVRHP5QWQo3WrbU9MsNb3LLi50VSNV43oLJzGQkq1a5VgncRg8yDLyrg3GlUIuxhj368TfWvIwPh/ojZHsXlPx0+l8RZ1Is15FCKOPzj7YHLJuR1XR5MS2ikQUz7yWvn4AnjxNDM/gFKxoN6YNgg=
before_install:
- openssl aes-256-cbc -K $encrypted_14dfe625469c_key -iv $encrypted_14dfe625469c_iv
  -in deploy.enc -out deploy -d
install:
- npm install --only=dev
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
- npm run build
after_success:
- "./scripts/deploy.sh"
